### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by sabinlazar** [bdeitte/scheduled-snapshots#1]
The OS is a Centos 6 64bit and it has python 3.3.3 installed.
Error bellow:

[root@ip-172 /]# python3 --version
Python 3.3.3
[root@ip-172 /]# python3 /usr/local/bin/ssbackup.py --volume-ids=vol-4gg4gg4 --expiry-days=7
Traceback (most recent call last):
 File "/usr/local/lib/python3.3/json/decoder.py", line 368, in raw_decode
   obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/bin/ssbackup.py", line 119, in <module>
   snapshots = createSnapshots(volumeIds)
 File "/usr/local/bin/ssbackup.py", line 56, in createSnapshots
   "--profile", profile
 File "/usr/local/lib/python3.3/json/**init**.py", line 319, in loads
   return _default_decoder.decode(s)
 File "/usr/local/lib/python3.3/json/decoder.py", line 352, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/local/lib/python3.3/json/decoder.py", line 370, in raw_decode
   raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by bdeitte** [comment]
Hi sabinlazar, the error above is saying that that aws command used to tag the snapshot is not returning any JSON.  Unfortunately, the script does not return any more information about why nothing is returned.  To find this information yourself, try this from the command-line:

```
aws ec2 create-tags --resources=vol-4gg4gg4 --tags Key=Name,Value=Backup12345,Key=Group,Value=ssbackup --profile ssbackup
```

**Comment by sabinlazar** [comment]
Hi. I ran the aws command above and indeed it's not retuning any JSON. Isn't that ok?
The command works fine and sets the key and value correctly on aws volume.

Also, the python script generates the correct snapshot on aws, tagged with the group ssbackup and the date.

root@ip-172~]# aws ec2 describe-snapshots --filters "Name=tag-key,Values=Group","Name=tag-value,Values=ssbackup"  --profile ssbackup
{
    "Snapshots": [
        {
            "Description": "Backup 2016-02-21",
            "Tags": [
                {
                    "Value": "Backup 2016-02-21",
                    "Key": "Name"
                },
                {
                    "Value": "ssbackup",
                    "Key": "Group"
                }
            ],
            "Encrypted": false,
            "VolumeId": "vol-xxxxxx",
            "State": "completed",
            "VolumeSize": 8,
            "Progress": "100%",
            "StartTime": "2016-02-20T23:47:45.000Z",
            "SnapshotId": "snap-e07dxxxx",
            "OwnerId": "xxxx"
        }
    ]
}
[root@ip-172~]#

**Comment by bdeitte** [comment]
Huh, interesting.  The same command (well with a different volume ID) returns the following for me:

```
{
    "return": "true"
}
```

I take it the AWS CLI works differently on some platforms, or perhaps you're on an older version of it?  This is what I am running:

```
aws --version
aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-48-generic
```

In any case, I'll see if I can fix up the script to handle this case.

**Comment by bdeitte** [comment]
This should be fixed up with the latest script.  Let me know if you still see an issue.

**Comment by sabinlazar** [comment]
It works now. Thank you.
