### ISSUE TITLE
multiple --volume-ids

### ISSUE THREAD

**Issue by sabinlazar** [bdeitte/scheduled-snapshots#3]
Hello. The script works as intended for a single volume id argument passed to it. If you pass multiple volume-ids arguments it only creates a snapshot for the last argument, no matter how many you use.
The example bellow only creates a snapshot for --volume-ids=vol-xxxx2.

[root@ip-172 ~]# aws --version
aws-cli/1.10.6 Python/3.3.3 Linux/2.6.32-573.7.1.el6.x86_64 botocore/1.3.28

[root@ip-172 ~]# python3 /usr/local/bin/ssbackup.py --volume-ids=vol-xxxxx1 --volume-ids=vol-xxxx2 --expiry-days=7
Creating snapshots
Deleting old snapshots
Processing completed
[root@ip-172 ~]#

**Comment by bdeitte** [comment]
Ah, so the comment in the source file is wrong I believe.  Try this instead:

```
 python3 /usr/local/bin/ssbackup.py --volume-ids=vol-xxxxx1,vol-xxxx2 
```

If that works, I'll fix up the comment.

**Comment by sabinlazar** [comment]
I tried the comma separated values and I get this error now. It generates the snaphots but without the Name tag.
[root@ip-172- ~]# python3 /usr/local/bin/ssbackup.py --volume-ids=vol-xxxxx1,vol-xxxxx2 --expiry-days=7
Creating snapshots

A client error (InvalidID) occurred when calling the CreateTags operation: The ID 'snap-4bd9ad40 snap-9be93591' is not valid
Deleting old snapshots
Processing completed
[root@ip-172- ~]#

**Comment by bdeitte** [comment]
Huh interesting.  This looks like a bug with the existing script I brought in here.  I can't look at it more right now, but I will try this out with multiple IDs myself and try to fix up in the next few days.

**Comment by bdeitte** [comment]
Sure enough, this does not look like it ever worked.  I tried it out and it should be good now.
